version: "3.7"

services:

    service_1:        
        image: tbytautas/service_1        
        # ports:
            # - "5000:5000"
        networks:
            - tadas_network
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_DB_NAME=${MYSQL_DB_NAME}
        depends_on:
            - service_4
            - service_2
            - service_3
        deploy:
            replicas: 3


    service_2:        
        image: tbytautas/service_2        
        networks:
            - tadas_network
        deploy:
            replicas: 3

    service_3:        
        image: tbytautas/service_3        
        networks:
            - tadas_network
        deploy:
            replicas: 3

    service_4:        
        image: tbytautas/service_4        
        networks:
            - tadas_network
        deploy:
            replicas: 3
    
    nginx:
        image: tbytautas/nginxsfia2
        ports:
            - "80:80"
        networks:
            - tadas_network
        depends_on:
            - service_1
            - service_2
            - service_3
            - service_4
        deploy:
            replicas: 3

networks:
    tadas_network:
        driver: overlay
    
