---
- name: NGINX
  hosts: swarm-worker
  become: true
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX Service
    service:
      name: nginx
      state: started

# run assible command "ansible-playbook playbook.yml"